export const BODY_PART_OPTIONS = [
  { value: "any", label: "Any muscle" },
  { value: "abductors", label: "Abductors" },
  { value: "abs", label: "Abs" },
  { value: "adductors", label: "Adductors" },
  { value: "biceps", label: "Biceps" },
  { value: "calves", label: "Calves" },
  { value: "cardiovascular system", label: "Cardiovascular System" },
  { value: "shoulders", label: "Shoulders" },
  { value: "forearms", label: "Forearms" },
  { value: "glutes", label: "Glutes" },
  { value: "hamstrings", label: "Hamstrings" },
  { value: "lats", label: "Lats" },
  { value: "chest", label: "Chest" },
  { value: "quads", label: "Quads" },
  { value: "traps", label: "Traps" },
  { value: "triceps", label: "Triceps" },
  { value: "upper back", label: "Upper Back" },
];

export const EQUIPMENT_OPTIONS = [
  { value: "any", label: "Any equipment" },
  { value: "assisted", label: "Assisted" },
  { value: "band", label: "Band" },
  { value: "barbell", label: "Barbell" },
  { value: "body weight", label: "Body Weight" },
  { value: "bosu ball", label: "Bosu Ball" },
  { value: "cable", label: "Cable" },
  { value: "dumbbell", label: "Dumbbell" },
  { value: "elliptical machine", label: "Elliptical Machine" },
  { value: "ez barbell", label: "Ez Barbell" },
  { value: "hammer", label: "Hammer" },
  { value: "kettlebell", label: "Kettlebell" },
  { value: "leverage machine", label: "Leverage Machine" },
  { value: "medicine ball", label: "Medicine Ball" },
  { value: "olympic barbell", label: "Olympic Barbell" },
  { value: "resistance band", label: "Resistance Band" },
  { value: "roller", label: "Roller" },
  { value: "rope", label: "Rope" },
  { value: "skierg machine", label: "Skierg Machine" },
  { value: "sled machine", label: "Sled Machine" },
  { value: "smith machine", label: "Smith Machine" },
  { value: "stability ball", label: "Stability Ball" },
  { value: "stationary bike", label: "Stationary Bike" },
  { value: "stepmill machine", label: "Stepmill Machine" },
  { value: "tire", label: "Tire" },
  { value: "trap bar", label: "Trap Bar" },
  { value: "upper body ergometer", label: "Upper Body Ergometer" },
  { value: "weighted", label: "Weighted" },
  { value: "wheel roller", label: "Wheel Roller" },
];

export const EXERCISES_PER_PAGE = 33;

export const WORKOUTS_PER_PAGE = 4;
